{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "composecommon",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "lee.vioson",
          "module": "lyftoast",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "lee.vioson",
          "module": "uikit",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-swiperefresh",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager-indicators",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "io.github.shenzhen2017",
          "module": "compose-refreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.chargemap.compose",
          "module": "numberpicker",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "composecommon-0.1.2.aar",
          "url": "composecommon-0.1.2.aar",
          "size": 616864,
          "sha512": "54aaceab5862abf1b1754f216cbfd2999156e3649ddfa4a59285b3867de2892c141c33ca541466bfe4cad2a8e22faa0dcb6970091fac7d0954293f3b39e97089",
          "sha256": "7525628b50eed4c4820f89e4530d03aeae3b4a71698aef37c8a9451d8a2bd072",
          "sha1": "6b1c693cafb2800774ea5425fb2dc5d5673c93ad",
          "md5": "5778b98b705ece20ed30393d99c247db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "lee.vioson",
          "module": "lyftoast",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "lee.vioson",
          "module": "uikit",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-swiperefresh",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager-indicators",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "io.github.shenzhen2017",
          "module": "compose-refreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.chargemap.compose",
          "module": "numberpicker",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "composecommon-0.1.2.aar",
          "url": "composecommon-0.1.2.aar",
          "size": 616864,
          "sha512": "54aaceab5862abf1b1754f216cbfd2999156e3649ddfa4a59285b3867de2892c141c33ca541466bfe4cad2a8e22faa0dcb6970091fac7d0954293f3b39e97089",
          "sha256": "7525628b50eed4c4820f89e4530d03aeae3b4a71698aef37c8a9451d8a2bd072",
          "sha1": "6b1c693cafb2800774ea5425fb2dc5d5673c93ad",
          "md5": "5778b98b705ece20ed30393d99c247db"
        }
      ]
    }
  ]
}
