{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.maitarou",
    "module": "radioscanner",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "radioscanner-0.0.3.aar",
          "url": "radioscanner-0.0.3.aar",
          "size": 610219,
          "sha512": "3d22c7971e8f865c06ab81739f226205d7d8e9eae59f4ffc9cf89de75a961920f7a3d102efad1ac7a7ed47a562f25db5a96f552a20b15c4e8d8a34f18bbd5915",
          "sha256": "443689a2592df4345760972ed56c77c68455e0433102ae42e167f5af9158f6ea",
          "sha1": "359ca099dca1daed9cea0e62125a8c9b3345055a",
          "md5": "c697a356872697a8727e31b7b6905f2b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "radioscanner-0.0.3.aar",
          "url": "radioscanner-0.0.3.aar",
          "size": 610219,
          "sha512": "3d22c7971e8f865c06ab81739f226205d7d8e9eae59f4ffc9cf89de75a961920f7a3d102efad1ac7a7ed47a562f25db5a96f552a20b15c4e8d8a34f18bbd5915",
          "sha256": "443689a2592df4345760972ed56c77c68455e0433102ae42e167f5af9158f6ea",
          "sha1": "359ca099dca1daed9cea0e62125a8c9b3345055a",
          "md5": "c697a356872697a8727e31b7b6905f2b"
        }
      ]
    }
  ]
}
