{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "commonutils",
    "version": "0.0.1-alpha003",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.0.1-alpha003.aar",
          "url": "commonutils-0.0.1-alpha003.aar",
          "size": 228631,
          "sha512": "8d498b8462b52604a2ff9f5305bdce3c807080fbfea0a4b36b19b0609092586a11ff340926adec3b7bbfbf9c7b4b3ad8cb0354cffb6e95d25c308df81e7bc45a",
          "sha256": "a36f22980f123dbb9689ce436ddd15bd0bf62ca6747d4d80bc546f7807e0cbc5",
          "sha1": "0c7a8157c38acb1d8557da48d5ce996746ca06a2",
          "md5": "ea56d99b551f98e8ad3b2fa4b4f1fa74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.0.1-alpha003.aar",
          "url": "commonutils-0.0.1-alpha003.aar",
          "size": 228631,
          "sha512": "8d498b8462b52604a2ff9f5305bdce3c807080fbfea0a4b36b19b0609092586a11ff340926adec3b7bbfbf9c7b4b3ad8cb0354cffb6e95d25c308df81e7bc45a",
          "sha256": "a36f22980f123dbb9689ce436ddd15bd0bf62ca6747d4d80bc546f7807e0cbc5",
          "sha1": "0c7a8157c38acb1d8557da48d5ce996746ca06a2",
          "md5": "ea56d99b551f98e8ad3b2fa4b4f1fa74"
        }
      ]
    }
  ]
}
