{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "composecommon",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "lee.vioson",
          "module": "lyftoast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "uikit",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-swiperefresh",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager-indicators",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-animation",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "io.github.shenzhen2017",
          "module": "compose-refreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.chargemap.compose",
          "module": "numberpicker",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "composecommon-0.1.0.aar",
          "url": "composecommon-0.1.0.aar",
          "size": 602698,
          "sha512": "524aa2846120d608843a934fc5c880f7459ee726cf8444cde9923b5ec12aa5c6e0971fa7cc1842a87cf633295833f931148eae8c578925ffb94c5a6ba433c667",
          "sha256": "b3e8fae052c697db1711e7827f8dd660f99d44d67dc990eae5a8026042d2f133",
          "sha1": "8e5aa9d72f89db375b05f38ded36103e75468401",
          "md5": "bdcd64d6ce8bd90f4b5e27f253deae1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "lee.vioson",
          "module": "lyftoast",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "uikit",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-swiperefresh",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager-indicators",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-animation",
          "version": {
            "requires": "0.30.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "io.github.shenzhen2017",
          "module": "compose-refreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.chargemap.compose",
          "module": "numberpicker",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "composecommon-0.1.0.aar",
          "url": "composecommon-0.1.0.aar",
          "size": 602698,
          "sha512": "524aa2846120d608843a934fc5c880f7459ee726cf8444cde9923b5ec12aa5c6e0971fa7cc1842a87cf633295833f931148eae8c578925ffb94c5a6ba433c667",
          "sha256": "b3e8fae052c697db1711e7827f8dd660f99d44d67dc990eae5a8026042d2f133",
          "sha1": "8e5aa9d72f89db375b05f38ded36103e75468401",
          "md5": "bdcd64d6ce8bd90f4b5e27f253deae1d"
        }
      ]
    }
  ]
}
