{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "lyftoast",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lyftoast-0.0.4.aar",
          "url": "lyftoast-0.0.4.aar",
          "size": 25752,
          "sha512": "67b6ae50103e97db20b4fb990c80c154c58aab52717efb591cf9b6bdad64e3f18d11f9eb8ed25e9633c01ab9af65edc0bcf745682c161a67a23f13e82a54bd43",
          "sha256": "8887879944a5fb11a84a5d00ad31bc079199287cfc5ab15f6acb4cf9b14fbe2d",
          "sha1": "038df028246c3a74ee27d2f3348a1a6727b88345",
          "md5": "b99cd1d74370e3d4820f084395550614"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lyftoast-0.0.4.aar",
          "url": "lyftoast-0.0.4.aar",
          "size": 25752,
          "sha512": "67b6ae50103e97db20b4fb990c80c154c58aab52717efb591cf9b6bdad64e3f18d11f9eb8ed25e9633c01ab9af65edc0bcf745682c161a67a23f13e82a54bd43",
          "sha256": "8887879944a5fb11a84a5d00ad31bc079199287cfc5ab15f6acb4cf9b14fbe2d",
          "sha1": "038df028246c3a74ee27d2f3348a1a6727b88345",
          "md5": "b99cd1d74370e3d4820f084395550614"
        }
      ]
    }
  ]
}
