{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "commonutils",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.0.20.aar",
          "url": "commonutils-0.0.20.aar",
          "size": 238106,
          "sha512": "96e7902641b1d74cb799250d677344a94ab076146b41408f2703fa318f8f739b9039e39cd8f6cee5b9479bf6af461515fd42a58f50503a9ab20efe3da0ade9c6",
          "sha256": "b07dddc573854973c5f35f6e0e4fb8df818bf3b38ddd3f239c68be01182bf649",
          "sha1": "fdd568fbc71bd83a01cd5fc9f99f82a4054f52ed",
          "md5": "013aad7f29a2b071e52fb62a99c7b133"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.0.20.aar",
          "url": "commonutils-0.0.20.aar",
          "size": 238106,
          "sha512": "96e7902641b1d74cb799250d677344a94ab076146b41408f2703fa318f8f739b9039e39cd8f6cee5b9479bf6af461515fd42a58f50503a9ab20efe3da0ade9c6",
          "sha256": "b07dddc573854973c5f35f6e0e4fb8df818bf3b38ddd3f239c68be01182bf649",
          "sha1": "fdd568fbc71bd83a01cd5fc9f99f82a4054f52ed",
          "md5": "013aad7f29a2b071e52fb62a99c7b133"
        }
      ]
    }
  ]
}
