{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "commonutils",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.1.5.aar",
          "url": "commonutils-0.1.5.aar",
          "size": 236663,
          "sha512": "8e0934cd1cec5917629b460fd6f261598bfeca590f107cf774fc550adfd1b3b1bcf063aa6a44b00ac2b4793757946a03667d773a491976efe0000b07be21c323",
          "sha256": "82cf37115d91e0d39a6bb39be90fbbb61b835fbb5524b80709e57a9f6e5af267",
          "sha1": "7356274e61673ecd1fe70a23160e97a8b4aab45b",
          "md5": "008e314e811365f604ff0f9ed28ccfe7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.1.5.aar",
          "url": "commonutils-0.1.5.aar",
          "size": 236663,
          "sha512": "8e0934cd1cec5917629b460fd6f261598bfeca590f107cf774fc550adfd1b3b1bcf063aa6a44b00ac2b4793757946a03667d773a491976efe0000b07be21c323",
          "sha256": "82cf37115d91e0d39a6bb39be90fbbb61b835fbb5524b80709e57a9f6e5af267",
          "sha1": "7356274e61673ecd1fe70a23160e97a8b4aab45b",
          "md5": "008e314e811365f604ff0f9ed28ccfe7"
        }
      ]
    }
  ]
}
