{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "appinput",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.21.aar",
          "url": "appinput-0.0.21.aar",
          "size": 47450,
          "sha512": "823d62b6b1a147ffee5fe4742cca07ea070bb523210b4af200858dba0068e475324010459699e2d0b7a9705ebc7e56a6cdd0ed213b7e05aec33e29cf475d5aaf",
          "sha256": "01767ae34751375e3ccda2a292b6ae6e62c9304d62eb4af921f02def37e48c4e",
          "sha1": "7f7b1755a1460fcb74fa56b2071d85f96eeb8e71",
          "md5": "986ff6577c3ab72c7fedb696abeb2dee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.21.aar",
          "url": "appinput-0.0.21.aar",
          "size": 47450,
          "sha512": "823d62b6b1a147ffee5fe4742cca07ea070bb523210b4af200858dba0068e475324010459699e2d0b7a9705ebc7e56a6cdd0ed213b7e05aec33e29cf475d5aaf",
          "sha256": "01767ae34751375e3ccda2a292b6ae6e62c9304d62eb4af921f02def37e48c4e",
          "sha1": "7f7b1755a1460fcb74fa56b2071d85f96eeb8e71",
          "md5": "986ff6577c3ab72c7fedb696abeb2dee"
        }
      ]
    }
  ]
}
