{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "appinput",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.21.aar",
          "url": "appinput-0.0.21.aar",
          "size": 54939,
          "sha512": "120fec80a9f56805225ececa6ac2e210ab8343e2d11002eafe182cebacb7830bb712445201ee644ac72538d5ae1eb3ddb10a3062875c3d99f88d1db945db7560",
          "sha256": "9f1dd85c7f56ade8ad26dc54bd714faf5c226c0079766342775637245e5d7c4c",
          "sha1": "0c1db04d203e045c61652212a064e71e3efee559",
          "md5": "3440173f6546044ebecf132ffe556647"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.21.aar",
          "url": "appinput-0.0.21.aar",
          "size": 54939,
          "sha512": "120fec80a9f56805225ececa6ac2e210ab8343e2d11002eafe182cebacb7830bb712445201ee644ac72538d5ae1eb3ddb10a3062875c3d99f88d1db945db7560",
          "sha256": "9f1dd85c7f56ade8ad26dc54bd714faf5c226c0079766342775637245e5d7c4c",
          "sha1": "0c1db04d203e045c61652212a064e71e3efee559",
          "md5": "3440173f6546044ebecf132ffe556647"
        }
      ]
    }
  ]
}
