{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.maitarou",
    "module": "radioscanner",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "radioscanner-0.1.0.aar",
          "url": "radioscanner-0.1.0.aar",
          "size": 610291,
          "sha512": "99e76bd600e549b61c7698ca5e80209596aaa9d41847c1a178b4d997228bf3b33db87747712dec9a2770ccbea561acc9049890e461bd11a304dbfb80d8b43033",
          "sha256": "351d215c62d4cec9463924955290f05d435c968dee77e122b0ed15cab630bf31",
          "sha1": "754f5d7ad8c5ae777e904f2f1b4125969f525b9b",
          "md5": "d2cf0200b34c70e061310824b5bb5d98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "radioscanner-0.1.0.aar",
          "url": "radioscanner-0.1.0.aar",
          "size": 610291,
          "sha512": "99e76bd600e549b61c7698ca5e80209596aaa9d41847c1a178b4d997228bf3b33db87747712dec9a2770ccbea561acc9049890e461bd11a304dbfb80d8b43033",
          "sha256": "351d215c62d4cec9463924955290f05d435c968dee77e122b0ed15cab630bf31",
          "sha1": "754f5d7ad8c5ae777e904f2f1b4125969f525b9b",
          "md5": "d2cf0200b34c70e061310824b5bb5d98"
        }
      ]
    }
  ]
}
