{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "appinput",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.11.aar",
          "url": "appinput-0.0.11.aar",
          "size": 30313,
          "sha512": "20b49206cd7060c1b9746e91a1d426283c14a691c95c25644668077266fea46ef12c5bc8ff0601548e2dbbd8b39a690f3bb9f6fc1d121f6a452465fb66f8a411",
          "sha256": "2f8b698bea6dafcddb7d888e9ce459c8fbeccb6e68e32ba5de9fed79e030a70f",
          "sha1": "0dc1dfd3ee1221b2e4376bfb427b42bf94c9d15e",
          "md5": "bcc08c3fdb11ad4e15b6c7c8fc1da310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.11.aar",
          "url": "appinput-0.0.11.aar",
          "size": 30313,
          "sha512": "20b49206cd7060c1b9746e91a1d426283c14a691c95c25644668077266fea46ef12c5bc8ff0601548e2dbbd8b39a690f3bb9f6fc1d121f6a452465fb66f8a411",
          "sha256": "2f8b698bea6dafcddb7d888e9ce459c8fbeccb6e68e32ba5de9fed79e030a70f",
          "sha1": "0dc1dfd3ee1221b2e4376bfb427b42bf94c9d15e",
          "md5": "bcc08c3fdb11ad4e15b6c7c8fc1da310"
        }
      ]
    }
  ]
}
