{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "uikit",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "uikit-0.1.3.aar",
          "url": "uikit-0.1.3.aar",
          "size": 22081,
          "sha512": "991d5f119f58ea22066f8f0d3b95323003dac1c565aaeca6bc361923418c31ed82cea99993358b574004d63e3ea60ef39e9f78981f866e6a17aaa1429be2760e",
          "sha256": "c035dc0a6e63c891971dc3812bfc4cee8178071d1c73531d27206373a46e7c2a",
          "sha1": "fab3eab327f645a7c733383a323d191e88e360a6",
          "md5": "a89a0449c3a84c7dd484653d6e42250f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "uikit-0.1.3.aar",
          "url": "uikit-0.1.3.aar",
          "size": 22081,
          "sha512": "991d5f119f58ea22066f8f0d3b95323003dac1c565aaeca6bc361923418c31ed82cea99993358b574004d63e3ea60ef39e9f78981f866e6a17aaa1429be2760e",
          "sha256": "c035dc0a6e63c891971dc3812bfc4cee8178071d1c73531d27206373a46e7c2a",
          "sha1": "fab3eab327f645a7c733383a323d191e88e360a6",
          "md5": "a89a0449c3a84c7dd484653d6e42250f"
        }
      ]
    }
  ]
}
