{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "commonutils",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.1.0.aar",
          "url": "commonutils-0.1.0.aar",
          "size": 236770,
          "sha512": "7b0bd3e6c4f62fe4fa6bc825d8a2b6a305deed162f382fa8d26b82b53ee99dfc07a542e3dd4f328ba655e4f39f68a34760c3326d5ca75ee56b607503c01b9e86",
          "sha256": "ec107cbe4a9f022cbbb09a399a639cea362eb193a1ab5701eab1d67cfbe01c0f",
          "sha1": "d1e1307b76eda7cc1023ce1ca3c918d42f33cd3b",
          "md5": "f07f533fd5c353c2ad5a216cd605e756"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.1.0.aar",
          "url": "commonutils-0.1.0.aar",
          "size": 236770,
          "sha512": "7b0bd3e6c4f62fe4fa6bc825d8a2b6a305deed162f382fa8d26b82b53ee99dfc07a542e3dd4f328ba655e4f39f68a34760c3326d5ca75ee56b607503c01b9e86",
          "sha256": "ec107cbe4a9f022cbbb09a399a639cea362eb193a1ab5701eab1d67cfbe01c0f",
          "sha1": "d1e1307b76eda7cc1023ce1ca3c918d42f33cd3b",
          "md5": "f07f533fd5c353c2ad5a216cd605e756"
        }
      ]
    }
  ]
}
