{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "uikit",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "uikit-0.0.2.aar",
          "url": "uikit-0.0.2.aar",
          "size": 20419,
          "sha512": "17dec464110dcd101deef088ee7afe4747aca355e9dbb5af150705f64285f80ff25bc53df7e1a0202d1448bd65e11a0a716977f82357eb2376f565be44597a24",
          "sha256": "b94900341cff450eb545d93f72920d171309bdb589864623e4062a38f8f50b5f",
          "sha1": "cc7b5d129f9cefc1eb7a531adcad6069e1a08cdb",
          "md5": "9ef1d35d30020b47a7425582d6040882"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "uikit-0.0.2.aar",
          "url": "uikit-0.0.2.aar",
          "size": 20419,
          "sha512": "17dec464110dcd101deef088ee7afe4747aca355e9dbb5af150705f64285f80ff25bc53df7e1a0202d1448bd65e11a0a716977f82357eb2376f565be44597a24",
          "sha256": "b94900341cff450eb545d93f72920d171309bdb589864623e4062a38f8f50b5f",
          "sha1": "cc7b5d129f9cefc1eb7a531adcad6069e1a08cdb",
          "md5": "9ef1d35d30020b47a7425582d6040882"
        }
      ]
    }
  ]
}
