{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "commonutils",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.0.8.aar",
          "url": "commonutils-0.0.8.aar",
          "size": 237939,
          "sha512": "017b41bf2204db88cadc3bc21d33d1b4c2e5716dd9922923b16d8f1b80ab127867edacf9f601eb58ac4bd39afc5c6f822082af6e91f6a7188fd6f4c4036e87db",
          "sha256": "e8016375375adbba25550a57ca4e23e03bef3f0af71e766b6267890fb5d5e53b",
          "sha1": "2daebf4aa48c34d64e37f08b035da188a7aaa847",
          "md5": "48149a7141b32f96f0e668f6d3a250a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "commonutils-0.0.8.aar",
          "url": "commonutils-0.0.8.aar",
          "size": 237939,
          "sha512": "017b41bf2204db88cadc3bc21d33d1b4c2e5716dd9922923b16d8f1b80ab127867edacf9f601eb58ac4bd39afc5c6f822082af6e91f6a7188fd6f4c4036e87db",
          "sha256": "e8016375375adbba25550a57ca4e23e03bef3f0af71e766b6267890fb5d5e53b",
          "sha1": "2daebf4aa48c34d64e37f08b035da188a7aaa847",
          "md5": "48149a7141b32f96f0e668f6d3a250a9"
        }
      ]
    }
  ]
}
