{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "appinput",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.19.aar",
          "url": "appinput-0.0.19.aar",
          "size": 47227,
          "sha512": "6a831244bffa5f14c1ce1bf0110732d661064bd64a19e665cb7a3aea57693c09fdcf1f8648187540dab5732ca4b3f98e1ab0ba17c34cb5de917e536ff6f1e80d",
          "sha256": "71e4eabc528c8eca3c33ea82dc038893e796e19445a88db03064d7a796d26598",
          "sha1": "8d252b77ba617b3cf0a950c9be5696a58594628e",
          "md5": "65df229a237fc2ae5fa4c0db81543bb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.19"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.19.aar",
          "url": "appinput-0.0.19.aar",
          "size": 47227,
          "sha512": "6a831244bffa5f14c1ce1bf0110732d661064bd64a19e665cb7a3aea57693c09fdcf1f8648187540dab5732ca4b3f98e1ab0ba17c34cb5de917e536ff6f1e80d",
          "sha256": "71e4eabc528c8eca3c33ea82dc038893e796e19445a88db03064d7a796d26598",
          "sha1": "8d252b77ba617b3cf0a950c9be5696a58594628e",
          "md5": "65df229a237fc2ae5fa4c0db81543bb9"
        }
      ]
    }
  ]
}
