{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "uikit",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "uikit-0.0.20.aar",
          "url": "uikit-0.0.20.aar",
          "size": 20447,
          "sha512": "11f306288e4d1f84ae0ad1172546e2601390e455b9409edfbd5dc9770cdf5965ef248f0628a11951fdc236ac7717b74643a84748167697c991bd8970a9d16e73",
          "sha256": "de4021b96c90b9b0d0c43bbd7871cf66259fa138485b63efecb49e0db93f3c4a",
          "sha1": "044aa97cf8ec90a6a3b4a8e4cb0440abdedd74de",
          "md5": "d3e25fb75c4a5aff48daaa147d8cf9ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "uikit-0.0.20.aar",
          "url": "uikit-0.0.20.aar",
          "size": 20447,
          "sha512": "11f306288e4d1f84ae0ad1172546e2601390e455b9409edfbd5dc9770cdf5965ef248f0628a11951fdc236ac7717b74643a84748167697c991bd8970a9d16e73",
          "sha256": "de4021b96c90b9b0d0c43bbd7871cf66259fa138485b63efecb49e0db93f3c4a",
          "sha1": "044aa97cf8ec90a6a3b4a8e4cb0440abdedd74de",
          "md5": "d3e25fb75c4a5aff48daaa147d8cf9ce"
        }
      ]
    }
  ]
}
