{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "lyftoast",
    "version": "0.0.1-alpha007",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lyftoast-0.0.1-alpha007.aar",
          "url": "lyftoast-0.0.1-alpha007.aar",
          "size": 25773,
          "sha512": "2c4120fa9c216a61e6f8cb69b9618360e8f0315f53f172effcaef5135023acb7919ac6d64a6ae238143d7b09f1f161b43edb4afe888b4eda3fae7c9f8884c2af",
          "sha256": "8fa27b4bf1ec23f4bf517b7f3c6990aa369d8f9c4e5f577fc56e8c43b4e342cf",
          "sha1": "6561fbf356a5598c8ce685edd4ac833a9f4d3a72",
          "md5": "016966be4f8acd20346f439ed9651dfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lyftoast-0.0.1-alpha007.aar",
          "url": "lyftoast-0.0.1-alpha007.aar",
          "size": 25773,
          "sha512": "2c4120fa9c216a61e6f8cb69b9618360e8f0315f53f172effcaef5135023acb7919ac6d64a6ae238143d7b09f1f161b43edb4afe888b4eda3fae7c9f8884c2af",
          "sha256": "8fa27b4bf1ec23f4bf517b7f3c6990aa369d8f9c4e5f577fc56e8c43b4e342cf",
          "sha1": "6561fbf356a5598c8ce685edd4ac833a9f4d3a72",
          "md5": "016966be4f8acd20346f439ed9651dfb"
        }
      ]
    }
  ]
}
