{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "lyftoast",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "lyftoast-1.0.0.aar",
          "url": "lyftoast-1.0.0.aar",
          "size": 24495,
          "sha512": "9220b1ffd8f3df8f83483f521799834165734a6cb564b19463ff66a2be1ada9a84b4267f3317a267d4835789af4b99c9ecb3d35265de622b93c2859635fca41d",
          "sha256": "d143e84fcb2c0befdcd369ee2b79ca9d4b5933da4f0808e345372b1665feb3b8",
          "sha1": "7dcb6715d666e35a4f781fdc4433918d1b7a40ab",
          "md5": "1214e70fd09a556efc639fa2791c2606"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "lyftoast-1.0.0.aar",
          "url": "lyftoast-1.0.0.aar",
          "size": 24495,
          "sha512": "9220b1ffd8f3df8f83483f521799834165734a6cb564b19463ff66a2be1ada9a84b4267f3317a267d4835789af4b99c9ecb3d35265de622b93c2859635fca41d",
          "sha256": "d143e84fcb2c0befdcd369ee2b79ca9d4b5933da4f0808e345372b1665feb3b8",
          "sha1": "7dcb6715d666e35a4f781fdc4433918d1b7a40ab",
          "md5": "1214e70fd09a556efc639fa2791c2606"
        }
      ]
    }
  ]
}
