{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "composecommon",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "lee.vioson",
          "module": "lyftoast",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "lee.vioson",
          "module": "uikit",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-swiperefresh",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager-indicators",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-animation",
          "version": {
            "requires": "0.16.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.github.shenzhen2017",
          "module": "compose-refreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.chargemap.compose",
          "module": "numberpicker",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "composecommon-0.0.7.aar",
          "url": "composecommon-0.0.7.aar",
          "size": 597729,
          "sha512": "8c0cb5f847516d6e888243a5766f12749cfc46679409c6b2b4647a30950d428b9138a9431d818b651d32a16d2901a0295f9f757c3f8d0d514d7f76b71af1a653",
          "sha256": "7c827f60607a82cdaeb040f082609268dfc424cd56590d5e3ec53b57ca0bac2b",
          "sha1": "1de452beb65d415d2a47e0d2469551b4e0c0fee1",
          "md5": "9f93e5aea8b1b733d07958fb8875b5c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "lee.vioson",
          "module": "lyftoast",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "lee.vioson",
          "module": "uikit",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-swiperefresh",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-pager-indicators",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-animation",
          "version": {
            "requires": "0.16.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.github.shenzhen2017",
          "module": "compose-refreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.chargemap.compose",
          "module": "numberpicker",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "composecommon-0.0.7.aar",
          "url": "composecommon-0.0.7.aar",
          "size": 597729,
          "sha512": "8c0cb5f847516d6e888243a5766f12749cfc46679409c6b2b4647a30950d428b9138a9431d818b651d32a16d2901a0295f9f757c3f8d0d514d7f76b71af1a653",
          "sha256": "7c827f60607a82cdaeb040f082609268dfc424cd56590d5e3ec53b57ca0bac2b",
          "sha1": "1de452beb65d415d2a47e0d2469551b4e0c0fee1",
          "md5": "9f93e5aea8b1b733d07958fb8875b5c8"
        }
      ]
    }
  ]
}
