{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "appinput",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.13.aar",
          "url": "appinput-0.0.13.aar",
          "size": 47004,
          "sha512": "6268685e1a6e1f59477cac78ab56de105c317328fe784da6ae6d989c318ee46cbcc87862efd7ab142a737d1c6c307dbf41225c9cc784fd557d69cc812b07bbee",
          "sha256": "626a50cc794a70f379c5a6d213b0f6843eaf4791d4ca95a7f65ae0aa6ae4b716",
          "sha1": "e84cb9e79b907f4cc0aa6ac397c67e7eeef9ab84",
          "md5": "819e411ea17d7a0ced2d027cbba0e693"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.13.aar",
          "url": "appinput-0.0.13.aar",
          "size": 47004,
          "sha512": "6268685e1a6e1f59477cac78ab56de105c317328fe784da6ae6d989c318ee46cbcc87862efd7ab142a737d1c6c307dbf41225c9cc784fd557d69cc812b07bbee",
          "sha256": "626a50cc794a70f379c5a6d213b0f6843eaf4791d4ca95a7f65ae0aa6ae4b716",
          "sha1": "e84cb9e79b907f4cc0aa6ac397c67e7eeef9ab84",
          "md5": "819e411ea17d7a0ced2d027cbba0e693"
        }
      ]
    }
  ]
}
