{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.vioson",
    "module": "appinput",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.22.aar",
          "url": "appinput-0.0.22.aar",
          "size": 54945,
          "sha512": "d0b01d2363f441efd0e5ad3d74477fa7373b258c26d4485b0421fe3fade1c2599cd9d928ab730b9469c88d1f5b1e3f02f9c9fd2947335027912f11ea42ef2cfa",
          "sha256": "eae08b6335a141451081c0284d3ea74dfa239314bf08a62f3a8cf15c0b576a34",
          "sha1": "baa5e61352127541a56a3b10a8f6d05553103f27",
          "md5": "e8ac75979027befefb401620b6b99a4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "lee.vioson",
          "module": "commonutils",
          "version": {
            "requires": "0.0.22"
          }
        }
      ],
      "files": [
        {
          "name": "appinput-0.0.22.aar",
          "url": "appinput-0.0.22.aar",
          "size": 54945,
          "sha512": "d0b01d2363f441efd0e5ad3d74477fa7373b258c26d4485b0421fe3fade1c2599cd9d928ab730b9469c88d1f5b1e3f02f9c9fd2947335027912f11ea42ef2cfa",
          "sha256": "eae08b6335a141451081c0284d3ea74dfa239314bf08a62f3a8cf15c0b576a34",
          "sha1": "baa5e61352127541a56a3b10a8f6d05553103f27",
          "md5": "e8ac75979027befefb401620b6b99a4b"
        }
      ]
    }
  ]
}
