{
  "formatVersion": "1.1",
  "component": {
    "group": "lee.maitarou",
    "module": "radioscanner",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "radioscanner-0.0.4.aar",
          "url": "radioscanner-0.0.4.aar",
          "size": 610216,
          "sha512": "1fa80f6648a3d577b90aa74012273b1bc079789765a8cf1df28f8cf12a3b7b54c68e2540f380941d5a13695b9162be0c459cb58b111f864908e0084daba93580",
          "sha256": "d6bcba2e885abc7d9fdd894ab65a76676e3d2aa0a74e11aa87fa7a8f43edd29f",
          "sha1": "7e32270f08dd27d9ffa9c6cd3450ea275c19ed9b",
          "md5": "f72d93b2ed9172420e3382f5f57e7fb5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "radioscanner-0.0.4.aar",
          "url": "radioscanner-0.0.4.aar",
          "size": 610216,
          "sha512": "1fa80f6648a3d577b90aa74012273b1bc079789765a8cf1df28f8cf12a3b7b54c68e2540f380941d5a13695b9162be0c459cb58b111f864908e0084daba93580",
          "sha256": "d6bcba2e885abc7d9fdd894ab65a76676e3d2aa0a74e11aa87fa7a8f43edd29f",
          "sha1": "7e32270f08dd27d9ffa9c6cd3450ea275c19ed9b",
          "md5": "f72d93b2ed9172420e3382f5f57e7fb5"
        }
      ]
    }
  ]
}
